# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PinOnDiskMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(537, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(537, 700))
        MainWindow.setMaximumSize(QtCore.QSize(537, 700))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(16, 4, 501, 85))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 5, 0, 5)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.portCombo = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.portCombo.setObjectName("portCombo")
        self.gridLayout.addWidget(self.portCombo, 1, 0, 1, 1)
        self.conectarBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.conectarBtn.setObjectName("conectarBtn")
        self.gridLayout.addWidget(self.conectarBtn, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.widget.setMinimumSize(QtCore.QSize(26, 26))
        self.widget.setMaximumSize(QtCore.QSize(26, 26))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.labelNotConnected = QtWidgets.QLabel(self.widget)
        self.labelNotConnected.setGeometry(QtCore.QRect(0, 0, 26, 26))
        self.labelNotConnected.setMaximumSize(QtCore.QSize(26, 26))
        self.labelNotConnected.setText("")
        self.labelNotConnected.setPixmap(QtGui.QPixmap("icons/led-red-on.png"))
        self.labelNotConnected.setScaledContents(True)
        self.labelNotConnected.setObjectName("labelNotConnected")
        self.labelConnected = QtWidgets.QLabel(self.widget)
        self.labelConnected.setGeometry(QtCore.QRect(0, 0, 26, 26))
        self.labelConnected.setMaximumSize(QtCore.QSize(26, 26))
        self.labelConnected.setText("")
        self.labelConnected.setPixmap(QtGui.QPixmap("icons/green-led-on.png"))
        self.labelConnected.setScaledContents(True)
        self.labelConnected.setObjectName("labelConnected")
        self.gridLayout.addWidget(self.widget, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(16, 560, 505, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.startBtn.setEnabled(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_4.addWidget(self.startBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pauseBtn.setEnabled(False)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_4.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_4.addWidget(self.stopBtn)
        self.testBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testBtn.setEnabled(False)
        self.testBtn.setGeometry(QtCore.QRect(16, 528, 505, 28))
        self.testBtn.setObjectName("testBtn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(16, 612, 505, 53))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        self.progressLabel.setScaledContents(False)
        self.progressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.horizontalLayout_6.addWidget(self.progressLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.speedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.speedLabel.setFont(font)
        self.speedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_6.addWidget(self.speedLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.estimatedEndLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.estimatedEndLabel.setFont(font)
        self.estimatedEndLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.estimatedEndLabel.setObjectName("estimatedEndLabel")
        self.horizontalLayout_6.addWidget(self.estimatedEndLabel)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(4, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(16, 104, 501, 417))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(4, 8, 493, 385))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("font-size: 14px;")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(8, 24, 469, 353))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 13px")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.experimentNameInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.experimentNameInput.setEnabled(False)
        self.experimentNameInput.setStyleSheet("font-size: 13px;")
        self.experimentNameInput.setObjectName("experimentNameInput")
        self.verticalLayout_3.addWidget(self.experimentNameInput)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("font-size: 13px")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pathInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pathInput.setEnabled(False)
        self.pathInput.setStyleSheet("font-size: 13px;")
        self.pathInput.setReadOnly(True)
        self.pathInput.setObjectName("pathInput")
        self.horizontalLayout_2.addWidget(self.pathInput)
        self.pathBrowseBtn = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.pathBrowseBtn.setStyleSheet("font-size: 13px;")
        self.pathBrowseBtn.setObjectName("pathBrowseBtn")
        self.horizontalLayout_2.addWidget(self.pathBrowseBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setStyleSheet("font-size: 13px")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.distanciaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.distanciaInput.setStyleSheet("font-size: 13px;")
        self.distanciaInput.setObjectName("distanciaInput")
        self.horizontalLayout.addWidget(self.distanciaInput)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setStyleSheet("font-size: 13px")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setStyleSheet("font-size: 13px")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.radioCombo.setStyleSheet("font-size: 13px;")
        self.radioCombo.setObjectName("radioCombo")
        self.horizontalLayout_3.addWidget(self.radioCombo)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setStyleSheet("font-size: 13px")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setStyleSheet("font-size: 13px")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cargaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.cargaInput.setStyleSheet("font-size: 13px;")
        self.cargaInput.setText("")
        self.cargaInput.setObjectName("cargaInput")
        self.horizontalLayout_5.addWidget(self.cargaInput)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setStyleSheet("font-size: 13px")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.widget_2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(4, 8, 493, 385))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setStyleSheet("font-size: 14px;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(8, 20, 465, 357))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOperador = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelOperador.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOperador.setStyleSheet("font-size: 13px;")
        self.labelOperador.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOperador.setObjectName("labelOperador")
        self.verticalLayout.addWidget(self.labelOperador)
        self.operarioInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.operarioInput.setStyleSheet("font-size: 13px;")
        self.operarioInput.setInputMask("")
        self.operarioInput.setText("")
        self.operarioInput.setObjectName("operarioInput")
        self.verticalLayout.addWidget(self.operarioInput)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setStyleSheet("font-size: 13px;")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.probetaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.probetaInput.setStyleSheet("font-size: 13px;")
        self.probetaInput.setText("")
        self.probetaInput.setObjectName("probetaInput")
        self.verticalLayout.addWidget(self.probetaInput)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setStyleSheet("font-size: 13px;")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.materialInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.materialInput.setStyleSheet("font-size: 13px;")
        self.materialInput.setText("")
        self.materialInput.setClearButtonEnabled(False)
        self.materialInput.setObjectName("materialInput")
        self.verticalLayout.addWidget(self.materialInput)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setStyleSheet("font-size: 13px;")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.durezaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.durezaInput.setStyleSheet("font-size: 13px;")
        self.durezaInput.setText("")
        self.durezaInput.setObjectName("durezaInput")
        self.verticalLayout.addWidget(self.durezaInput)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setStyleSheet("font-size: 13px;")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tratamientoInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tratamientoInput.setStyleSheet("font-size: 13px;")
        self.tratamientoInput.setText("")
        self.tratamientoInput.setObjectName("tratamientoInput")
        self.verticalLayout.addWidget(self.tratamientoInput)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setStyleSheet("font-size: 13px;")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.bolillaCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.bolillaCombo.setObjectName("bolillaCombo")
        self.verticalLayout.addWidget(self.bolillaCombo)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setStyleSheet("font-size: 13px;")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.diametroBolillaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.diametroBolillaInput.setStyleSheet("font-size: 13px;")
        self.diametroBolillaInput.setText("")
        self.diametroBolillaInput.setObjectName("diametroBolillaInput")
        self.verticalLayout.addWidget(self.diametroBolillaInput)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POD App"))
        self.conectarBtn.setText(_translate("MainWindow", "Conectar"))
        self.label_3.setText(_translate("MainWindow", "Seleccione el puerto del controlador"))
        self.startBtn.setText(_translate("MainWindow", "Empezar"))
        self.pauseBtn.setText(_translate("MainWindow", "Pausar"))
        self.stopBtn.setText(_translate("MainWindow", "Detener"))
        self.testBtn.setText(_translate("MainWindow", "Prueba"))
        self.progressLabel.setText(_translate("MainWindow", "554 de 11605 vueltas"))
        self.speedLabel.setText(_translate("MainWindow", "10.0 cm/s"))
        self.estimatedEndLabel.setText(_translate("MainWindow", "Finaliza: 13:15"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuración del ensayo"))
        self.label_2.setText(_translate("MainWindow", "Nombre del experimento"))
        self.label.setText(_translate("MainWindow", "Seleccione carpeta de destino para guardar datos del ensayo:"))
        self.pathBrowseBtn.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Distancia"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "Radio"))
        self.label_7.setText(_translate("MainWindow", "mm"))
        self.label_8.setText(_translate("MainWindow", "Carga"))
        self.label_9.setText(_translate("MainWindow", "N"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_2), _translate("MainWindow", "Configuración del ensayo"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Datos del ensayo"))
        self.labelOperador.setText(_translate("MainWindow", "Operador"))
        self.operarioInput.setPlaceholderText(_translate("MainWindow", "Operador"))
        self.label_11.setText(_translate("MainWindow", "Probeta"))
        self.probetaInput.setPlaceholderText(_translate("MainWindow", "Probeta"))
        self.label_12.setText(_translate("MainWindow", "Material"))
        self.materialInput.setPlaceholderText(_translate("MainWindow", "Material"))
        self.label_13.setText(_translate("MainWindow", "Dureza (HV)"))
        self.durezaInput.setPlaceholderText(_translate("MainWindow", "Dureza"))
        self.label_14.setText(_translate("MainWindow", "Tratamiento"))
        self.tratamientoInput.setPlaceholderText(_translate("MainWindow", "Tratamiento"))
        self.label_15.setText(_translate("MainWindow", "Bolilla"))
        self.label_16.setText(_translate("MainWindow", "Diámetro de la bolilla (mm)"))
        self.diametroBolillaInput.setPlaceholderText(_translate("MainWindow", "Diámetro de la bolilla"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Datos del ensayo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
