# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PinOnDiskApp.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import serial.tools.list_ports

def loadSerialPorts():
    comlist = [port.device for port in serial.tools.list_ports.comports()]
    for port in comlist:
        ui.portCombo.addItem(port)




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(516, 516)
        MainWindow.setMinimumSize(QtCore.QSize(516, 516))
        MainWindow.setMaximumSize(QtCore.QSize(516, 516))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(16, 4, 481, 59))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.portCombo = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.portCombo.setObjectName("portCombo")
        self.gridLayout.addWidget(self.portCombo, 1, 0, 1, 1)
        self.connectedCheck = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.connectedCheck.setEnabled(True)
        self.connectedCheck.setCheckable(False)
        self.connectedCheck.setObjectName("connectedCheck")
        self.gridLayout.addWidget(self.connectedCheck, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.conectarBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.conectarBtn.setObjectName("conectarBtn")
        self.gridLayout.addWidget(self.conectarBtn, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(8, 88, 493, 285))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(8, 24, 481, 249))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.experimentNameInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.experimentNameInput.setObjectName("experimentNameInput")
        self.verticalLayout_3.addWidget(self.experimentNameInput)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pathInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pathInput.setEnabled(False)
        self.pathInput.setReadOnly(True)
        self.pathInput.setObjectName("pathInput")
        self.horizontalLayout_2.addWidget(self.pathInput)
        self.pathBrowseBtn = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.pathBrowseBtn.setObjectName("pathBrowseBtn")
        self.horizontalLayout_2.addWidget(self.pathBrowseBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.distanciaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.distanciaInput.setObjectName("distanciaInput")
        self.horizontalLayout.addWidget(self.distanciaInput)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.radioCombo.setObjectName("radioCombo")
        self.horizontalLayout_3.addWidget(self.radioCombo)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(16, 384, 485, 73))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.startBtn.setEnabled(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_4.addWidget(self.startBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pauseBtn.setEnabled(False)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_4.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_4.addWidget(self.stopBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POD App"))
        self.connectedCheck.setText(_translate("MainWindow", "Conectado"))
        self.label_3.setText(_translate("MainWindow", "Seleccione puerto del controlador"))
        self.conectarBtn.setText(_translate("MainWindow", "Conectar"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuración de experimento"))
        self.label_2.setText(_translate("MainWindow", "Nombre del experimento"))
        self.label.setText(_translate("MainWindow", "Seleccione carpeta de destino para guardar datos del ensayo:"))
        self.pathBrowseBtn.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Distancia"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "Radio"))
        self.label_7.setText(_translate("MainWindow", "mm"))
        self.startBtn.setText(_translate("MainWindow", "Empezar"))
        self.pauseBtn.setText(_translate("MainWindow", "Pausar"))
        self.stopBtn.setText(_translate("MainWindow", "Detener"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    loadSerialPorts()
    MainWindow.show()
    sys.exit(app.exec_())
