# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PinOnDiskMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(510, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(510, 618))
        MainWindow.setMaximumSize(QtCore.QSize(510, 618))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(16, 4, 481, 85))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 5, 0, 5)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.portCombo = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.portCombo.setObjectName("portCombo")
        self.gridLayout.addWidget(self.portCombo, 1, 0, 1, 1)
        self.conectarBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.conectarBtn.setObjectName("conectarBtn")
        self.gridLayout.addWidget(self.conectarBtn, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.widget.setMinimumSize(QtCore.QSize(26, 26))
        self.widget.setMaximumSize(QtCore.QSize(26, 26))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.labelNotConnected = QtWidgets.QLabel(self.widget)
        self.labelNotConnected.setGeometry(QtCore.QRect(0, 0, 26, 26))
        self.labelNotConnected.setMaximumSize(QtCore.QSize(26, 26))
        self.labelNotConnected.setText("")
        self.labelNotConnected.setPixmap(QtGui.QPixmap("icons/led-red-on.png"))
        self.labelNotConnected.setScaledContents(True)
        self.labelNotConnected.setObjectName("labelNotConnected")
        self.labelConnected = QtWidgets.QLabel(self.widget)
        self.labelConnected.setGeometry(QtCore.QRect(0, 0, 26, 26))
        self.labelConnected.setMaximumSize(QtCore.QSize(26, 26))
        self.labelConnected.setText("")
        self.labelConnected.setPixmap(QtGui.QPixmap("icons/green-led-on.png"))
        self.labelConnected.setScaledContents(True)
        self.labelConnected.setObjectName("labelConnected")
        self.gridLayout.addWidget(self.widget, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(8, 100, 493, 325))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(8, 24, 481, 285))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.experimentNameInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.experimentNameInput.setObjectName("experimentNameInput")
        self.verticalLayout_3.addWidget(self.experimentNameInput)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pathInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.pathInput.setEnabled(False)
        self.pathInput.setReadOnly(True)
        self.pathInput.setObjectName("pathInput")
        self.horizontalLayout_2.addWidget(self.pathInput)
        self.pathBrowseBtn = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.pathBrowseBtn.setObjectName("pathBrowseBtn")
        self.horizontalLayout_2.addWidget(self.pathBrowseBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.distanciaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.distanciaInput.setObjectName("distanciaInput")
        self.horizontalLayout.addWidget(self.distanciaInput)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.radioCombo.setObjectName("radioCombo")
        self.horizontalLayout_3.addWidget(self.radioCombo)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cargaInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.cargaInput.setText("")
        self.cargaInput.setObjectName("cargaInput")
        self.horizontalLayout_5.addWidget(self.cargaInput)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(8, 472, 493, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.startBtn.setEnabled(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_4.addWidget(self.startBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pauseBtn.setEnabled(False)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_4.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_4.addWidget(self.stopBtn)
        self.testBtn = QtWidgets.QPushButton(self.centralwidget)
        self.testBtn.setEnabled(False)
        self.testBtn.setGeometry(QtCore.QRect(8, 440, 493, 28))
        self.testBtn.setObjectName("testBtn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(8, 524, 493, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.progressLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        self.progressLabel.setScaledContents(False)
        self.progressLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_2.addWidget(self.progressLabel, 1, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 50)
        self.gridLayout_2.setRowMinimumHeight(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POD App"))
        self.conectarBtn.setText(_translate("MainWindow", "Conectar"))
        self.label_3.setText(_translate("MainWindow", "Seleccione puerto del controlador"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuración de experimento"))
        self.label_2.setText(_translate("MainWindow", "Nombre del experimento"))
        self.label.setText(_translate("MainWindow", "Seleccione carpeta de destino para guardar datos del ensayo:"))
        self.pathBrowseBtn.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Distancia"))
        self.label_6.setText(_translate("MainWindow", "m"))
        self.label_5.setText(_translate("MainWindow", "Radio"))
        self.label_7.setText(_translate("MainWindow", "mm"))
        self.label_8.setText(_translate("MainWindow", "Carga"))
        self.label_9.setText(_translate("MainWindow", "N"))
        self.startBtn.setText(_translate("MainWindow", "Empezar"))
        self.pauseBtn.setText(_translate("MainWindow", "Pausar"))
        self.stopBtn.setText(_translate("MainWindow", "Detener"))
        self.testBtn.setText(_translate("MainWindow", "Prueba"))
        self.progressLabel.setText(_translate("MainWindow", "554 de 11605 vueltas"))
